"""test3

Revision ID: 460b0a59d611
Revises: b11e334ecc0d
Create Date: 2020-09-16 19:34:49.986699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '460b0a59d611'
down_revision = 'b11e334ecc0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('mobile', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'mobile')
    # ### end Alembic commands ###
